Endgamepopup
annalieseschropp/checkers pull request #86
Opened 2021-11-07 01:35 UTC by imckechn

Finished the popups, and wrote tests for the popups. Which all pass. 

For using the popups:
On the gameboard screen click the quit button in the top right and you have the option to quit the game or return to the game.
Once the game ends you will get a popup that tells you who won the game the score of the game. And it will allow the user to quit the game or restart it with the same settings as the previous game. 

To test:
Open the test runner and the tests appear under the popup title.

2021-11-07 16:06 UTC, DJ-CO requested changes
I’ll make some comments on specific parts of the code, but I’ll leave a summary here. Some issues need to be addressed:
1) Please figure out why there are so many unnecessary files changed in this PR, and then remove them. This was an issue in another PR, and it caused us to essentially redo the work in a new branch.
2) In general, please don’t leave empty if statements or obsolete commented out code.
3) “Once the game ends you will get a popup that tells you who won the game the score of the game”
    * If you test a full game, you will find that this simply isn’t true. This is likely because you are comparing enums to strings, instead of using the enums. As a rule of thumb, never compare enums to strings; the enums exist for a reason.
    * Don’t worry too much about fixing this until you get to the next point:
4) None of the code added belongs in the MoveController class. Please move that code somewhere else; the Board class would be a fine option, as Board is responsible for most of the UI Related game actions
    * You’ll notice that the MoveController class didn’t extend MonoBehaviour; that was not an accident, and should be a huge red flag. The MoveController does nothing UI related, and requires no part of MonoBehaviour; it should be kept that way for cohesion. If you dive into the board code (specifically, the “MoveControl() method of the board class (Board.cs)” that I explicitly referred to when you asked earlier), you’ll see that the Board handles all of the UI, and simply creates a MoveController as a utility for decision making.
    * Another red flag: the code you added to display the end game popup is in a method called GetGameStatus(). If a method is called “Get___”, that is a sign that it is meant to return a value for informational purposes, and have no side effects in and of itself. This returned value can then be used by another class (in this case, Board) to have whatever side effect is needed. The MoveController, however, just gets you this value, and it should be up to another class to decide what to do with it.
       * Imagine that, when we implement the AI, the AI checks a future (not present) board state using GetGameStatus() to see if it has a “forced checkmate sequence”, and sees that the future line it was calculating was a draw. Now imagine the user’s surprise when the game immediately ends, despite there still being 20+ moves before a possible draw, just because someone called GetGameStatus() on a board state that hadn’t even been reached yet, and that the AI probably wouldn’t have decided to play anyways. In short, GetGameStatus() should get the game status, nothing else.

2021-11-07 16:06 UTC, DJ-CO commented on Assets/Assets/Scripts/Board.cs
>          if(moveController.GetGameStatus() != CheckersMove.GameStatus.InProgress)
This if statement is already checking for the exact condition needed, and demonstrates how to properly use an instance of MoveController for information. This would be a better place to add the end game logic instead of in the MoveController itself.

2021-11-07 16:06 UTC, DJ-CO commented on Assets/Assets/Scripts/MoveController.cs
> +public class MoveController : MonoBehaviour
Red flag: if MoveController was perfectly functional without extending MonoBehaviour before, then adding this extension probably violates the class' single responsibility. Please move everything that was added to this file to a different class (using the Board class and the section that I've highlighted there would be fine).

2021-11-07 16:06 UTC, DJ-CO commented on Assets/Assets/Scripts/MoveController.cs
> -    {
Red flag: does this method still "GetGameStatus"? Not really. Now it forcefully initiates the end game sequence, which could catch some developers off guard in the future. This added code doesn't belong here; please move it to a different class.

2021-11-07 16:06 UTC, DJ-CO commented on Assets/Assets/Scripts/MoveController.cs
> +        if (count == 0)
Empty if statements and commented out code like this should be removed.

2021-11-07 16:06 UTC, DJ-CO commented on Assets/Assets/Scripts/MoveController.cs
> +        if (LegalMoveGenerator.GetGameStatus(boardState, currentTurn).ToString() == "WhiteWin")
These if statements don't appear to work. After moving this code out of the MoveControlller, please use the CheckersMove.GameStatus enums instead of comparing to strings.

2021-11-08 02:53 UTC, closed without merging

2021-11-08 02:54 UTC, imckechn commented
Made corrections. Going into a new PR.